### ISSUE TITLE
Read only mode

### ISSUE THREAD

**Issue by GulajavaMinistudio** [maslick/radiaSlider#12]
I cant find how to make this slider in Readonly mode. Any ideas ?

And how to customize the dot/circle color in front of slider ?

https://codepen.io/gulajavaministudio/pen/mdbXRzR

**Comment by maslick** [comment]
Hi @GulajavaMinistudio, read-only mode seems like a good feature. I will come up with sth when I get some free time.

**Comment by maslick** [comment]
@GulajavaMinistudio simply add ``readOnly: true`` to your Slider config.

**Comment by maslick** [comment]
resolving
