### ISSUE TITLE
dark mode causes artifacts

### ISSUE THREAD

**Issue by sandiz** [maslick/radiaSlider#5]
hi
thanks for great library!

i noticed that when using dark color scheme, there are some artifacts near the slider boundary. any way to fix that ?

![image](https://user-images.githubusercontent.com/5438703/55923686-508de800-5bbb-11e9-9f8c-af5fccc9a6da.png)
![image](https://user-images.githubusercontent.com/5438703/55923698-5b487d00-5bbb-11e9-9687-b99270087fb0.png)

**Comment by maslick** [comment]
Hi @sandiz, I have pushed the new version ``1.6.1``. Note also, I have supported HiDpi screens, so if you got one, sliders start to look smoother.

**Comment by sandiz** [comment]
looks super crispy now thanks!
